language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shalakhin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shalakhin/docker-react npm run test 

